### ISSUE TITLE
Can I get back the detailRibbon?

### ISSUE THREAD

**Issue by sannidhyaroy** [loof2736/scyfin#1]
How can I get back the detail ribbon that was set to transparent in this theme:
```
.detailRibbon {
    background: transparent !important;
}
```
Normally Jellyfin shows the backdrop there.

**Comment by loof2736** [comment]
If you paste this in your custom CSS (after where you imported scyfin) it would set back the color to default:

`.detailRibbon {background: rgba(32, 32, 32, 0.8) !important;}`

It isn't gonna look right though, since I modified a lot of stuff on the details page

But even with my theme, you should still be seeing the backdrop? Could you post a screenshot of what you are seeing / what you want?
