### ISSUE TITLE
Music is covered by drawer and drawer fails to hide

### ISSUE THREAD

**Issue by db-alakaboom** [loof2736/scyfin#10]
When playing back music in jellyfin the drawer is covering the left side of the seeking bar. Also hiding the drawer seems to only work in edge but not in Jellyfin Media Player even after restarting the app.  
![Captucre](https://github.com/loof2736/scyfin/assets/95014179/31d6096b-bac6-4fbf-9168-efeed93b8244)
![Capture2s](https://github.com/loof2736/scyfin/assets/95014179/757c1716-8b1b-42b1-afaa-04b2a80167e2)

**Comment by loof2736** [comment]
The drawer overlap is fixed in v1.0.12

Jellyfin Media Player is tricky, I've had a bunch of problems with it. It seems like random classes are present across the whole app. For instance, I have the hamburger button set to show on every page except the dashboard. In JMP though, every single page seems to have the dashboard class. So the the button gets hidden everywhere, not just the dashboard

Put this CSS snippet below (has to be below) where you imported the theme, it should fix the issue for JMP:

```
/* JMP Fix */
.layout-desktop .mainDrawer { left: -320px !important; z-index: 1099 !important; }
.layout-desktop .mainDrawerButton { display: inline-flex !important; }
```

This will show the hamburger button on the dashboard, though it doesn't do anything other than dim the screen
