### ISSUE TITLE
forgot password button at a strange position

### ISSUE THREAD

**Issue by Ewillian9** [loof2736/scyfin#22]
So i got this issue but maybe it's due to other css modification

![image](https://github.com/loof2736/scyfin/assets/156851131/0225bb97-c75f-4bb9-8e61-1dee77296bc2)

here my css

@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme-backdrop.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/episodelist/episodes_grid.css');
@import url('https://cdn.jsdelivr.net/gh/CTalvio/Ultrachromic/smallercast.css');
/*remove My Media title*/
.section0 .sectionTitle {display: none;}

/*remove next up*/
div.nextUpSection {display: none;}

/*hide jellyfin logo*/
.adminDrawerLogo img {content: url(imagepath) !important;} imgLogoIcon {content: url(imagepath) !important;} .pageTitleWithLogo {background-image: url(imagepath) !important;}

note that (imagepath) is intended, i want no logo, nothing, but maybe there's a more efficient way to do that.

**Comment by loof2736** [comment]
On the backdrops version of the theme the "forgot password" button has a blur effect by mistake, so that will be fixed in the next release. However, I'm not able to replicate the issue of positioning, even with the rest of the CSS tweaks you included. Even with the extra CSS the button is still in the correct place for me. What browser are you using?

**Comment by Ewillian9** [comment]
Thanks, i use firefox and chrome
